FROM @IMAGE@

MAINTAINER Stephen Gallagher <sgallagh@redhat.com>

RUN sed -i /etc/zypp/zypp.conf \
        -e "s/rpm.install.excludedocs = yes/rpm.install.excludedocs = no/"

RUN zypper install --no-confirm --no-recommends \
	clang \
	clang-checker \
	createrepo_c \
	elinks \
	file-devel \
	gcc \
	gcc-c++ \
	git-core \
	glib2-devel \
	gobject-introspection-devel \
	gtk-doc \
	help2man \
	libyaml-devel \
	meson \
	ninja \
	pkgconf \
	python-devel \
	python-gobject \
	python2-six \
	python3-autopep8 \
	python3-devel \
	python3-GitPython \
	python3-gobject \
	python3-pycodestyle \
	python-rpm-macros \
	rpm-build \
	rpm-devel \
	rpmdevtools \
	sudo \
	valgrind \
&& zypper clean --all
