FROM __IMAGE__

MAINTAINER Stephen Gallagher <sgallagh@redhat.com>

RUN pacman -Syu --needed --noconfirm \
	base-devel \
	file \
	glib2 \
	glib2-docs \
	gobject-introspection \
	gtk-doc \
	jq \
	libyaml \
	meson \
	python-gobject \
	python2-six \
&& pacman -Scc --noconfirm

RUN ln -sf /builddir/bindings/python/gi/overrides/Modulemd.py $(python3 -c "import gi; print(gi._overridesdir)")/Modulemd.py
