FROM @IMAGE@

MAINTAINER Stephen Gallagher <sgallagh@redhat.com>

RUN yum -y install epel-release \
    && yum -y --setopt=tsflags='' install \
        ccache \
        clang \
	createrepo_c \
	elinks \
	file-devel \
	gcc \
	gcc-c++ \
	git-core \
	glib2-devel \
	glib2-doc \
	gobject-introspection-devel \
	gtk-doc \
	libyaml-devel \
	meson \
	ninja-build \
	pkgconfig \
	python2-devel \
	python2-six \
	python-gobject-base \
	python36-devel \
	python36-gobject-base \
	python3-rpm-macros \
	redhat-rpm-config \
	rpm-build \
	rpm-devel \
	rpmdevtools \
	sudo \
    && yum -y clean all
