
/* This file is generated by glib-mkenums, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses. */

#pragma once

#include <glib-object.h>


G_BEGIN_DECLS

/* enumerations from "modulemd-defaults.h" */


GType modulemd_defaults_version_enum_get_type (void);
#define MODULEMD_TYPE_DEFAULTS_VERSION_ENUM (modulemd_defaults_version_enum_get_type())

/* enumerations from "modulemd-module-stream.h" */


GType modulemd_module_stream_version_enum_get_type (void);
#define MODULEMD_TYPE_MODULE_STREAM_VERSION_ENUM (modulemd_module_stream_version_enum_get_type())

G_END_DECLS

/* Generated data ends here */

