
/* This file is generated by glib-mkenums, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses. */

#include "modulemd-enums.h"
#include "modulemd.h"
#include "modulemd-buildopts.h"
#include "modulemd-component.h"
#include "modulemd-component-module.h"
#include "modulemd-component-rpm.h"
#include "modulemd-defaults.h"
#include "modulemd-defaults-v1.h"
#include "modulemd-dependencies.h"
#include "modulemd-deprecated.h"
#include "modulemd-module.h"
#include "modulemd-module-index.h"
#include "modulemd-module-index-merger.h"
#include "modulemd-module-stream.h"
#include "modulemd-module-stream-v1.h"
#include "modulemd-module-stream-v2.h"
#include "modulemd-profile.h"
#include "modulemd-service-level.h"
#include "modulemd-subdocument-info.h"
#include "modulemd-translation.h"
#include "modulemd-translation-entry.h"

#define C_ENUM(v) ((gint) v)
#define C_FLAGS(v) ((guint) v)

/* enumerations from "modulemd-defaults.h" */

GType
modulemd_defaults_version_enum_get_type (void)
{
  static volatile gsize gtype_id = 0;
  static const GEnumValue values[] = {
    { C_ENUM(MD_DEFAULTS_VERSION_ERROR), "MD_DEFAULTS_VERSION_ERROR", "error" },
    { C_ENUM(MD_DEFAULTS_VERSION_UNSET), "MD_DEFAULTS_VERSION_UNSET", "unset" },
    { C_ENUM(MD_DEFAULTS_VERSION_ONE), "MD_DEFAULTS_VERSION_ONE", "one" },
    { C_ENUM(MD_DEFAULTS_VERSION_LATEST), "MD_DEFAULTS_VERSION_LATEST", "latest" },
    { 0, NULL, NULL }
  };
  if (g_once_init_enter (&gtype_id)) {
    GType new_type = g_enum_register_static ("ModulemdDefaultsVersionEnum", values);
    g_once_init_leave (&gtype_id, new_type);
  }
  return (GType) gtype_id;
}

/* enumerations from "modulemd-module-stream.h" */

GType
modulemd_module_stream_version_enum_get_type (void)
{
  static volatile gsize gtype_id = 0;
  static const GEnumValue values[] = {
    { C_ENUM(MD_MODULESTREAM_VERSION_ERROR), "MD_MODULESTREAM_VERSION_ERROR", "error" },
    { C_ENUM(MD_MODULESTREAM_VERSION_UNSET), "MD_MODULESTREAM_VERSION_UNSET", "unset" },
    { C_ENUM(MD_MODULESTREAM_VERSION_ONE), "MD_MODULESTREAM_VERSION_ONE", "one" },
    { C_ENUM(MD_MODULESTREAM_VERSION_TWO), "MD_MODULESTREAM_VERSION_TWO", "two" },
    { C_ENUM(MD_MODULESTREAM_VERSION_LATEST), "MD_MODULESTREAM_VERSION_LATEST", "latest" },
    { 0, NULL, NULL }
  };
  if (g_once_init_enter (&gtype_id)) {
    GType new_type = g_enum_register_static ("ModulemdModuleStreamVersionEnum", values);
    g_once_init_leave (&gtype_id, new_type);
  }
  return (GType) gtype_id;
}

/* Generated data ends here */

