FROM @IMAGE@

MAINTAINER Tomasz Paweł Gajc <tpgxyz@gmail.com>

RUN dnf -y --setopt=install_weak_deps=False --setopt=tsflags='' install \
	clang \
	cmake \
	meson \
	ninja \
	rpmdevtools \
	sudo \
	valgrind \
	wget \
	gtk-doc \
	task-devel \
	'pkgconfig(zlib)' \
	'pkgconfig(gobject-introspection-1.0)' \
	'python3egg(autopep8)' \
	'python3dist(pygobject)' \
	'pkgconfig(yaml-0.1)' \
	'pkgconfig(rpm)' \
	magic-devel \
    && dnf -y clean all
