FROM @IMAGE@

MAINTAINER Stephen Gallagher <sgallagh@redhat.com>

RUN pacman -Syu --needed --noconfirm \
	base-devel \
	file \
	glib2 \
	glib2-docs \
	gobject-introspection \
	gtk-doc \
	help2man \
	jq \
	libyaml \
	meson \
	python-gobject \
	python2-six \
&& pacman -Scc --noconfirm
