FROM __IMAGE__

MAINTAINER Stephen Gallagher <sgallagh@redhat.com>

RUN dnf -y --setopt=install_weak_deps=False --setopt=tsflags='' install \
    clang \
    clang-analyzer \
    createrepo_c \
    curl \
    elinks \
    gcc \
    gcc-c++ \
    git-core \
    glib2-devel \
    /usr/share/gtk-doc/html/glib/index.html \
    gobject-introspection-devel \
    gtk-doc \
    jq \
    libyaml-devel \
    meson \
    ninja-build \
    openssl \
    pkgconf \
    popt-devel \
    python3-six \
    python3-autopep8 \
    python3-devel \
    python3-gitpython \
    python3-gobject3 \
    python3-pycodestyle \
    python3-rpm-macros \
    rpm-mageia-setup-build \
    rpm-build \
    rpm-devel \
    rpmdevtools \
    ruby \
    "rubygem(json)" \
    rubygems \
    sudo \
    valgrind \
    wget \
    && dnf -y clean all

RUN ln -sf /builddir/bindings/python/gi/overrides/Modulemd.py $(python3 -c "import gi; print(gi._overridesdir)")/Modulemd.py
